"""
Q5: AI Service Fallback System for KeaBuilder
Handles model failures and API timeouts gracefully
"""

import json
import asyncio
import time
from datetime import datetime


class AIProvider:
    """Base AI provider with health tracking"""
    
    def __init__(self, name, timeout=30):
        self.name = name
        self.timeout = timeout
        self.health = {"status": "healthy", "error_count": 0, "last_error": None}
    
    async def generate(self, request):
        # Simulated - in production calls actual API
        return {"provider": self.name, "result": f"Generated by {self.name}"}
    
    def mark_failed(self, error):
        self.health["error_count"] += 1
        self.health["last_error"] = str(error)
        if self.health["error_count"] >= 3:
            self.health["status"] = "unhealthy"
    
    def mark_success(self):
        self.health["error_count"] = 0
        self.health["status"] = "healthy"


class FallbackSystem:
    """Manages multiple AI providers with automatic fallback"""
    
    def __init__(self):
        self.providers = [
            AIProvider("openai", timeout=30),
            AIProvider("anthropic", timeout=30),
            AIProvider("local_model", timeout=60)
        ]
        self.cache = {}
        self.retry_queue = []
    
    async def generate_with_fallback(self, request):
        """Try each provider in order, fallback on failure"""
        
        # Check cache first
        cache_key = json.dumps(request, sort_keys=True)
        if cache_key in self.cache:
            return {**self.cache[cache_key], "source": "cache"}
        
        # Try each provider
        for provider in self.providers:
            if provider.health["status"] == "unhealthy":
                continue
            
            try:
                result = await asyncio.wait_for(
                    provider.generate(request),
                    timeout=provider.timeout
                )
                provider.mark_success()
                
                # Cache successful result
                self.cache[cache_key] = result
                return {**result, "source": "live"}
                
            except asyncio.TimeoutError:
                provider.mark_failed("Timeout")
                print(f"  ⚠️ {provider.name} timed out, trying next...")
                continue
                
            except Exception as e:
                provider.mark_failed(str(e))
                print(f"  ⚠️ {provider.name} failed: {e}, trying next...")
                continue
        
        # All providers failed - queue for retry
        return self.handle_all_failed(request)
    
    def handle_all_failed(self, request):
        """When all providers fail"""
        job = {
            "job_id": f"RETRY-{datetime.now().strftime('%Y%m%d%H%M%S')}",
            "request": request,
            "status": "queued_for_retry",
            "message": "All providers busy. Your content is being generated, we'll notify you shortly.",
            "retry_at": datetime.now().isoformat()
        }
        self.retry_queue.append(job)
        return job
    
    def get_health_status(self):
        """Dashboard health check for all providers"""
        return {p.name: p.health for p in self.providers}
    
    def get_best_provider(self):
        """Route to healthiest provider"""
        healthy = [p for p in self.providers if p.health["status"] == "healthy"]
        if healthy:
            return min(healthy, key=lambda p: p.health["error_count"])
        return self.providers[0]  # Fallback to first


class KeaBuilderUXHandler:
    """Handles user experience during failures"""
    
    def __init__(self):
        self.fallback = FallbackSystem()
    
    async def handle_user_request(self, request):
        """What user sees during the process"""
        
        # Step 1: Show loading state immediately
        response = {"status": "processing", "message": "Generating your content..."}
        
        # Step 2: Try generation with fallback
        result = await self.fallback.generate_with_fallback(request)
        
        # Step 3: Return appropriate response
        if result.get("status") == "queued_for_retry":
            return {
                "status": "delayed",
                "message": "Taking a bit longer than usual. We'll notify you when ready.",
                "job_id": result["job_id"],
                "show_retry_button": True
            }
        else:
            return {
                "status": "completed",
                "result": result,
                "message": "Content generated successfully!"
            }


if __name__ == "__main__":
    handler = KeaBuilderUXHandler()
    
    test_request = {
        "type": "image",
        "prompt": "Professional marketing banner",
        "user_id": "user_123"
    }
    
    print("=== Testing Fallback System ===")
    result = asyncio.run(handler.handle_user_request(test_request))
    print(json.dumps(result, indent=2, default=str))
    
    print("\n=== Provider Health ===")
    health = handler.fallback.get_health_status()
    print(json.dumps(health, indent=2))
